name: Build
on:
  push:
    tags:
          - 'MMCA-v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  # Mobile Crash Analyzer
  build-android:
    name: Mobile Crash Analyzer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: move Files
        run: |
          mkdir MonalMobileCrashAnalyzer_Deploy
          cp -av src/MobileCrashAnalyzer MonalMobileCrashAnalyzer_Deploy/MobileCrashAnalyzer
          cp -av src/shared MonalMobileCrashAnalyzer_Deploy/shared
          cp -av src/MobileCrashAnalyzer.py MonalMobileCrashAnalyzer_Deploy/main.py
          cp -av src/MobileCrashAnalyzer.spec MonalMobileCrashAnalyzer_Deploy/buildozer.spec

      - name: Build with Buildozer
        uses: Sobottasgithub/buildozer-action@v1.1.3
        id: buildozer
        with:
          workdir: MonalMobileCrashAnalyzer_Deploy
          buildozer_version: stable

      - uses: actions/upload-artifact@v4
        with:
          name: MobileCrashAnalyzer
          path: ${{ steps.buildozer.outputs.filename }}
            
  createrelease:
    name: Create Release
    runs-on: [ubuntu-latest]
    needs: build-android
    steps:
    - name: Load build artifacts
      uses: actions/download-artifact@v4
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
        target_commitish: master
        generate_release_notes: true
        body: |
          New release
        files: |
          MobileCrashAnalyzer*/*
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false