name: Build
on:
  push:
    tags:
          - 'MMCA-v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  # Mobile Crash Analyzer
  build-android:
    name: Mobile Crash Analyzer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: moveFiles
        run: |
          mkdir MonalMobileCrashAnalyzer_Deploy
          cp -av src/MobileCrashAnalyzer MonalMobileCrashAnalyzer_Deploy/MobileCrashAnalyzer
          cp -av src/shared MonalMobileCrashAnalyzer_Deploy/shared
          cp -av src/MobileCrashAnalyzer.py MonalMobileCrashAnalyzer_Deploy/main.py
          cp -av src/MobileCrashAnalyzer.spec MonalMobileCrashAnalyzer_Deploy/buildozer.spec

      - name: Build with Buildozer
        uses: Sobottasgithub/buildozer-action@v1.1.3
        id: buildozer
        with:
          workdir: MonalMobileCrashAnalyzer_Deploy
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
